DECLARE @idoc int 
DECLARE @data varchar(MAX)

SET @data = '
<items>
  <item>
    <Code>AD</Code>
    <Alpha3Code>AND</Alpha3Code>
    <NumericCode>20</NumericCode>
    <Name>Andorra</Name>
    <PhonePrefix>376</PhonePrefix>
    <DomainExtension>.ad</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>AE</Code>
    <Alpha3Code>ARE</Alpha3Code>
    <NumericCode>784</NumericCode>
    <Name>United Arab Emirates</Name>
    <PhonePrefix>971</PhonePrefix>
    <DomainExtension>.ae</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>AF</Code>
    <Alpha3Code>AFG</Alpha3Code>
    <NumericCode>4</NumericCode>
    <Name>Afghanistan</Name>
    <PhonePrefix>93</PhonePrefix>
    <DomainExtension>.af</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>AG</Code>
    <Alpha3Code>ATG</Alpha3Code>
    <NumericCode>28</NumericCode>
    <Name>Antigua and Barbuda</Name>
    <PhonePrefix>1268</PhonePrefix>
    <DomainExtension>.ag</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>AI</Code>
    <Alpha3Code>AIA</Alpha3Code>
    <NumericCode>660</NumericCode>
    <Name>Anguilla</Name>
    <PhonePrefix>1264</PhonePrefix>
    <DomainExtension>.ai</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>AL</Code>
    <Alpha3Code>ALB</Alpha3Code>
    <NumericCode>8</NumericCode>
    <Name>Albania</Name>
    <PhonePrefix>355</PhonePrefix>
    <DomainExtension>.al</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>AM</Code>
    <Alpha3Code>ARM</Alpha3Code>
    <NumericCode>51</NumericCode>
    <Name>Armenia</Name>
    <PhonePrefix>374</PhonePrefix>
    <DomainExtension>.am</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>AO</Code>
    <Alpha3Code>AGO</Alpha3Code>
    <NumericCode>24</NumericCode>
    <Name>Angola</Name>
    <PhonePrefix>244</PhonePrefix>
    <DomainExtension>.ao</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>AQ</Code>
    <Alpha3Code>ATA</Alpha3Code>
    <NumericCode>10</NumericCode>
    <Name>Antarctica</Name>
    <PhonePrefix>672</PhonePrefix>
    <DomainExtension>.aq</DomainExtension>
    <ContinentID>2</ContinentID>
  </item>
  <item>
    <Code>AR</Code>
    <Alpha3Code>ARG</Alpha3Code>
    <NumericCode>32</NumericCode>
    <Name>Argentina</Name>
    <PhonePrefix>54</PhonePrefix>
    <DomainExtension>.ar</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>AS</Code>
    <Alpha3Code>ASM</Alpha3Code>
    <NumericCode>16</NumericCode>
    <Name>American Samoa</Name>
    <PhonePrefix>1684</PhonePrefix>
    <DomainExtension>.as</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>AT</Code>
    <Alpha3Code>AUT</Alpha3Code>
    <NumericCode>40</NumericCode>
    <Name>Austria</Name>
    <PhonePrefix>43</PhonePrefix>
    <DomainExtension>.at</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>AU</Code>
    <Alpha3Code>AUS</Alpha3Code>
    <NumericCode>36</NumericCode>
    <Name>Australia</Name>
    <PhonePrefix>61</PhonePrefix>
    <DomainExtension>.au</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>AW</Code>
    <Alpha3Code>ABW</Alpha3Code>
    <NumericCode>533</NumericCode>
    <Name>Aruba</Name>
    <PhonePrefix>297</PhonePrefix>
    <DomainExtension>.aw</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>AZ</Code>
    <Alpha3Code>AZE</Alpha3Code>
    <NumericCode>31</NumericCode>
    <Name>Azerbaijan</Name>
    <PhonePrefix>994</PhonePrefix>
    <DomainExtension>.az</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>BA</Code>
    <Alpha3Code>BIH</Alpha3Code>
    <NumericCode>70</NumericCode>
    <Name>Bosnia and Herzegovina</Name>
    <PhonePrefix>387</PhonePrefix>
    <DomainExtension>.ba</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>BB</Code>
    <Alpha3Code>BRB</Alpha3Code>
    <NumericCode>52</NumericCode>
    <Name>Barbados</Name>
    <PhonePrefix>1246</PhonePrefix>
    <DomainExtension>.bb</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>BD</Code>
    <Alpha3Code>BGD</Alpha3Code>
    <NumericCode>50</NumericCode>
    <Name>Bangladesh</Name>
    <PhonePrefix>880</PhonePrefix>
    <DomainExtension>.bd</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>BE</Code>
    <Alpha3Code>BEL</Alpha3Code>
    <NumericCode>56</NumericCode>
    <Name>Belgium</Name>
    <PhonePrefix>32</PhonePrefix>
    <DomainExtension>.be</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>BF</Code>
    <Alpha3Code>BFA</Alpha3Code>
    <NumericCode>854</NumericCode>
    <Name>Burkina Faso</Name>
    <PhonePrefix>226</PhonePrefix>
    <DomainExtension>.bf</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>BG</Code>
    <Alpha3Code>BGR</Alpha3Code>
    <NumericCode>100</NumericCode>
    <Name>Bulgaria</Name>
    <PhonePrefix>359</PhonePrefix>
    <DomainExtension>.bg</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>BH</Code>
    <Alpha3Code>BHR</Alpha3Code>
    <NumericCode>48</NumericCode>
    <Name>Bahrain</Name>
    <PhonePrefix>973</PhonePrefix>
    <DomainExtension>.bh</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>BI</Code>
    <Alpha3Code>BDI</Alpha3Code>
    <NumericCode>108</NumericCode>
    <Name>Burundi</Name>
    <PhonePrefix>257</PhonePrefix>
    <DomainExtension>.bi</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>BJ</Code>
    <Alpha3Code>BEN</Alpha3Code>
    <NumericCode>204</NumericCode>
    <Name>Benin</Name>
    <PhonePrefix>229</PhonePrefix>
    <DomainExtension>.bj</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>BM</Code>
    <Alpha3Code>BMU</Alpha3Code>
    <NumericCode>60</NumericCode>
    <Name>Bermuda</Name>
    <PhonePrefix>1441</PhonePrefix>
    <DomainExtension>.bm</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>BN</Code>
    <Alpha3Code>BRN</Alpha3Code>
    <NumericCode>96</NumericCode>
    <Name>Brunei</Name>
    <PhonePrefix>673</PhonePrefix>
    <DomainExtension>.bn</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>BO</Code>
    <Alpha3Code>BOL</Alpha3Code>
    <NumericCode>68</NumericCode>
    <Name>Bolivia</Name>
    <PhonePrefix>591</PhonePrefix>
    <DomainExtension>.bo</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>BR</Code>
    <Alpha3Code>BRA</Alpha3Code>
    <NumericCode>76</NumericCode>
    <Name>Brazil</Name>
    <PhonePrefix>55</PhonePrefix>
    <DomainExtension>.br</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>BS</Code>
    <Alpha3Code>BHS</Alpha3Code>
    <NumericCode>44</NumericCode>
    <Name>Bahamas</Name>
    <PhonePrefix>1242</PhonePrefix>
    <DomainExtension>.bs</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>BT</Code>
    <Alpha3Code>BTN</Alpha3Code>
    <NumericCode>64</NumericCode>
    <Name>Bhutan</Name>
    <PhonePrefix>975</PhonePrefix>
    <DomainExtension>.bt</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>BW</Code>
    <Alpha3Code>BWA</Alpha3Code>
    <NumericCode>72</NumericCode>
    <Name>Botswana</Name>
    <PhonePrefix>267</PhonePrefix>
    <DomainExtension>.bw</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>BY</Code>
    <Alpha3Code>BLR</Alpha3Code>
    <NumericCode>112</NumericCode>
    <Name>Belarus</Name>
    <PhonePrefix>375</PhonePrefix>
    <DomainExtension>.by</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>BZ</Code>
    <Alpha3Code>BLZ</Alpha3Code>
    <NumericCode>84</NumericCode>
    <Name>Belize</Name>
    <PhonePrefix>501</PhonePrefix>
    <DomainExtension>.bz</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>CA</Code>
    <Alpha3Code>CAN</Alpha3Code>
    <NumericCode>124</NumericCode>
    <Name>Canada</Name>
    <PhonePrefix>1</PhonePrefix>
    <DomainExtension>.ca</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>CC</Code>
    <Alpha3Code>CCK</Alpha3Code>
    <NumericCode>166</NumericCode>
    <Name>Cocos Islands</Name>
    <PhonePrefix>61</PhonePrefix>
    <DomainExtension>.cc</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>CD</Code>
    <Alpha3Code>COD</Alpha3Code>
    <NumericCode>180</NumericCode>
    <Name>Dem. Republic of the Congo</Name>
    <PhonePrefix>243</PhonePrefix>
    <DomainExtension>.cd</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>CF</Code>
    <Alpha3Code>CAF</Alpha3Code>
    <NumericCode>140</NumericCode>
    <Name>Central African Republic</Name>
    <PhonePrefix>236</PhonePrefix>
    <DomainExtension>.cf</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>CG</Code>
    <Alpha3Code>COG</Alpha3Code>
    <NumericCode>178</NumericCode>
    <Name>Congo</Name>
    <PhonePrefix>242</PhonePrefix>
    <DomainExtension>.cg</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>CH</Code>
    <Alpha3Code>CHE</Alpha3Code>
    <NumericCode>756</NumericCode>
    <Name>Switzerland</Name>
    <PhonePrefix>41</PhonePrefix>
    <DomainExtension>.ch</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>CI</Code>
    <Alpha3Code>CIV</Alpha3Code>
    <NumericCode>384</NumericCode>
    <Name>Ivory Coast</Name>
    <PhonePrefix>225</PhonePrefix>
    <DomainExtension>.ci</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>CK</Code>
    <Alpha3Code>COK</Alpha3Code>
    <NumericCode>184</NumericCode>
    <Name>Cook Islands</Name>
    <PhonePrefix>682</PhonePrefix>
    <DomainExtension>.ck</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>CL</Code>
    <Alpha3Code>CHL</Alpha3Code>
    <NumericCode>152</NumericCode>
    <Name>Chile</Name>
    <PhonePrefix>56</PhonePrefix>
    <DomainExtension>.cl</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>CM</Code>
    <Alpha3Code>CMR</Alpha3Code>
    <NumericCode>120</NumericCode>
    <Name>Cameroon</Name>
    <PhonePrefix>237</PhonePrefix>
    <DomainExtension>.cm</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>CN</Code>
    <Alpha3Code>CHN</Alpha3Code>
    <NumericCode>156</NumericCode>
    <Name>China</Name>
    <PhonePrefix>86</PhonePrefix>
    <DomainExtension>.cn</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>CO</Code>
    <Alpha3Code>COL</Alpha3Code>
    <NumericCode>170</NumericCode>
    <Name>Colombia</Name>
    <PhonePrefix>57</PhonePrefix>
    <DomainExtension>.co</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>CR</Code>
    <Alpha3Code>CRI</Alpha3Code>
    <NumericCode>188</NumericCode>
    <Name>Costa Rica</Name>
    <PhonePrefix>506</PhonePrefix>
    <DomainExtension>.cr</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>CU</Code>
    <Alpha3Code>CUB</Alpha3Code>
    <NumericCode>192</NumericCode>
    <Name>Cuba</Name>
    <PhonePrefix>53</PhonePrefix>
    <DomainExtension>.cu</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>CV</Code>
    <Alpha3Code>CPV</Alpha3Code>
    <NumericCode>132</NumericCode>
    <Name>Cape Verde Islands</Name>
    <PhonePrefix>238</PhonePrefix>
    <DomainExtension>.cv</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>CW</Code>
    <Alpha3Code>ANT</Alpha3Code>
    <Name>Netherlands Antilles</Name>
    <PhonePrefix></PhonePrefix>
    <DomainExtension>.an</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>CX</Code>
    <Alpha3Code>CXR</Alpha3Code>
    <NumericCode>162</NumericCode>
    <Name>Christmas Island</Name>
    <PhonePrefix>61</PhonePrefix>
    <DomainExtension>.cx</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>CY</Code>
    <Alpha3Code>CYP</Alpha3Code>
    <NumericCode>196</NumericCode>
    <Name>Cyprus</Name>
    <PhonePrefix>357</PhonePrefix>
    <DomainExtension>.cy</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>CZ</Code>
    <Alpha3Code>CZE</Alpha3Code>
    <NumericCode>203</NumericCode>
    <Name>Czech Republic</Name>
    <PhonePrefix>420</PhonePrefix>
    <DomainExtension>.cz</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>DE</Code>
    <Alpha3Code>DEU</Alpha3Code>
    <NumericCode>276</NumericCode>
    <Name>Germany</Name>
    <PhonePrefix>49</PhonePrefix>
    <DomainExtension>.de</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>DJ</Code>
    <Alpha3Code>DJI</Alpha3Code>
    <NumericCode>262</NumericCode>
    <Name>Djibouti</Name>
    <PhonePrefix>253</PhonePrefix>
    <DomainExtension>.dj</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>DK</Code>
    <Alpha3Code>DNK</Alpha3Code>
    <NumericCode>208</NumericCode>
    <Name>Denmark</Name>
    <PhonePrefix>45</PhonePrefix>
    <DomainExtension>.dk</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>DM</Code>
    <Alpha3Code>DMA</Alpha3Code>
    <NumericCode>212</NumericCode>
    <Name>Dominica</Name>
    <PhonePrefix>1767</PhonePrefix>
    <DomainExtension>.dm</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>DO</Code>
    <Alpha3Code>DOM</Alpha3Code>
    <NumericCode>214</NumericCode>
    <Name>Dominican Republic</Name>
    <PhonePrefix>1809</PhonePrefix>
    <DomainExtension>.do</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>DZ</Code>
    <Alpha3Code>DZA</Alpha3Code>
    <NumericCode>12</NumericCode>
    <Name>Algeria</Name>
    <PhonePrefix>213</PhonePrefix>
    <DomainExtension>.dz</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>EC</Code>
    <Alpha3Code>ECU</Alpha3Code>
    <NumericCode>218</NumericCode>
    <Name>Ecuador</Name>
    <PhonePrefix>593</PhonePrefix>
    <DomainExtension>.ec</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>EE</Code>
    <Alpha3Code>EST</Alpha3Code>
    <NumericCode>233</NumericCode>
    <Name>Estonia</Name>
    <PhonePrefix>372</PhonePrefix>
    <DomainExtension>.ee</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>EG</Code>
    <Alpha3Code>EGY</Alpha3Code>
    <NumericCode>818</NumericCode>
    <Name>Egypt</Name>
    <PhonePrefix>20</PhonePrefix>
    <DomainExtension>.eg</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>ER</Code>
    <Alpha3Code>ERI</Alpha3Code>
    <NumericCode>232</NumericCode>
    <Name>Eritrea</Name>
    <PhonePrefix>291</PhonePrefix>
    <DomainExtension>.er</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>ES</Code>
    <Alpha3Code>ESP</Alpha3Code>
    <NumericCode>724</NumericCode>
    <Name>Spain</Name>
    <PhonePrefix>34</PhonePrefix>
    <DomainExtension>.es</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>ET</Code>
    <Alpha3Code>ETH</Alpha3Code>
    <NumericCode>231</NumericCode>
    <Name>Ethiopia</Name>
    <PhonePrefix>251</PhonePrefix>
    <DomainExtension>.et</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>FI</Code>
    <Alpha3Code>FIN</Alpha3Code>
    <NumericCode>246</NumericCode>
    <Name>Finland</Name>
    <PhonePrefix>358</PhonePrefix>
    <DomainExtension>.fi</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>FJ</Code>
    <Alpha3Code>FJI</Alpha3Code>
    <NumericCode>242</NumericCode>
    <Name>Fiji Islands</Name>
    <PhonePrefix>679</PhonePrefix>
    <DomainExtension>.fj</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>FK</Code>
    <Alpha3Code>FLK</Alpha3Code>
    <NumericCode>238</NumericCode>
    <Name>Falkland Islands</Name>
    <PhonePrefix>500</PhonePrefix>
    <DomainExtension>.fk</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>FM</Code>
    <Alpha3Code>FSM</Alpha3Code>
    <NumericCode>583</NumericCode>
    <Name>Federated States of Micronesia</Name>
    <PhonePrefix>691</PhonePrefix>
    <DomainExtension>.fm</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>FO</Code>
    <Alpha3Code>FRO</Alpha3Code>
    <NumericCode>234</NumericCode>
    <Name>Faroe Islands</Name>
    <PhonePrefix>298</PhonePrefix>
    <DomainExtension>.fo</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>FR</Code>
    <Alpha3Code>FRA</Alpha3Code>
    <NumericCode>250</NumericCode>
    <Name>France</Name>
    <PhonePrefix>33</PhonePrefix>
    <DomainExtension>.fr</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>GA</Code>
    <Alpha3Code>GAB</Alpha3Code>
    <NumericCode>266</NumericCode>
    <Name>Gabon Republic</Name>
    <PhonePrefix>241</PhonePrefix>
    <DomainExtension>.ga</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>GB</Code>
    <Alpha3Code>GBR</Alpha3Code>
    <NumericCode>826</NumericCode>
    <Name>United Kingdom</Name>
    <PhonePrefix>44</PhonePrefix>
    <DomainExtension>.uk</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>GD</Code>
    <Alpha3Code>GRD</Alpha3Code>
    <NumericCode>308</NumericCode>
    <Name>Grenada and Carriacuou</Name>
    <PhonePrefix>1473</PhonePrefix>
    <DomainExtension>.gd</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>GE</Code>
    <Alpha3Code>GEO</Alpha3Code>
    <NumericCode>268</NumericCode>
    <Name>Georgia</Name>
    <PhonePrefix>995</PhonePrefix>
    <DomainExtension>.ge</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>GF</Code>
    <Alpha3Code>GUF</Alpha3Code>
    <NumericCode>254</NumericCode>
    <Name>French Guiana</Name>
    <PhonePrefix></PhonePrefix>
    <DomainExtension>.gf</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>GH</Code>
    <Alpha3Code>GHA</Alpha3Code>
    <NumericCode>288</NumericCode>
    <Name>Ghana</Name>
    <PhonePrefix>233</PhonePrefix>
    <DomainExtension>.gh</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>GI</Code>
    <Alpha3Code>GIB</Alpha3Code>
    <NumericCode>292</NumericCode>
    <Name>Gibraltar</Name>
    <PhonePrefix>350</PhonePrefix>
    <DomainExtension>.gi</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>GL</Code>
    <Alpha3Code>GRL</Alpha3Code>
    <NumericCode>304</NumericCode>
    <Name>Greenland</Name>
    <PhonePrefix>299</PhonePrefix>
    <DomainExtension>.gl</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>GM</Code>
    <Alpha3Code>GMB</Alpha3Code>
    <NumericCode>270</NumericCode>
    <Name>Gambia</Name>
    <PhonePrefix>220</PhonePrefix>
    <DomainExtension>.gm</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>GN</Code>
    <Alpha3Code>GIN</Alpha3Code>
    <NumericCode>324</NumericCode>
    <Name>Guinea</Name>
    <PhonePrefix>224</PhonePrefix>
    <DomainExtension>.gn</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>GP</Code>
    <Alpha3Code>GLP</Alpha3Code>
    <NumericCode>312</NumericCode>
    <Name>Guadeloupe</Name>
    <PhonePrefix></PhonePrefix>
    <DomainExtension>.gp</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>GQ</Code>
    <Alpha3Code>GNQ</Alpha3Code>
    <NumericCode>226</NumericCode>
    <Name>Equatorial Guinea</Name>
    <PhonePrefix>240</PhonePrefix>
    <DomainExtension>.gq</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>GR</Code>
    <Alpha3Code>GRC</Alpha3Code>
    <NumericCode>300</NumericCode>
    <Name>Greece</Name>
    <PhonePrefix>30</PhonePrefix>
    <DomainExtension>.gr</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>GT</Code>
    <Alpha3Code>GTM</Alpha3Code>
    <NumericCode>320</NumericCode>
    <Name>Guatemala</Name>
    <PhonePrefix>502</PhonePrefix>
    <DomainExtension>.gt</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>GU</Code>
    <Alpha3Code>GUM</Alpha3Code>
    <NumericCode>316</NumericCode>
    <Name>Guam</Name>
    <PhonePrefix>1671</PhonePrefix>
    <DomainExtension>.gu</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>GW</Code>
    <Alpha3Code>GNB</Alpha3Code>
    <NumericCode>624</NumericCode>
    <Name>Guinea-Bissau</Name>
    <PhonePrefix>245</PhonePrefix>
    <DomainExtension>.gw</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>GY</Code>
    <Alpha3Code>GUY</Alpha3Code>
    <NumericCode>328</NumericCode>
    <Name>Guiana</Name>
    <PhonePrefix>592</PhonePrefix>
    <DomainExtension>.gf</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>HK</Code>
    <Alpha3Code>HKG</Alpha3Code>
    <NumericCode>344</NumericCode>
    <Name>Hong Kong</Name>
    <PhonePrefix>852</PhonePrefix>
    <DomainExtension>.hk</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>HN</Code>
    <Alpha3Code>HND</Alpha3Code>
    <NumericCode>340</NumericCode>
    <Name>Honduras</Name>
    <PhonePrefix>504</PhonePrefix>
    <DomainExtension>.hn</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>HR</Code>
    <Alpha3Code>HRV</Alpha3Code>
    <NumericCode>191</NumericCode>
    <Name>Croatia</Name>
    <PhonePrefix>385</PhonePrefix>
    <DomainExtension>.hr</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>HT</Code>
    <Alpha3Code>HTI</Alpha3Code>
    <NumericCode>332</NumericCode>
    <Name>Haiti</Name>
    <PhonePrefix>509</PhonePrefix>
    <DomainExtension>.ht</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>HU</Code>
    <Alpha3Code>HUN</Alpha3Code>
    <NumericCode>348</NumericCode>
    <Name>Hungary</Name>
    <PhonePrefix>36</PhonePrefix>
    <DomainExtension>.hu</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>ID</Code>
    <Alpha3Code>IDN</Alpha3Code>
    <NumericCode>360</NumericCode>
    <Name>Indonesia</Name>
    <PhonePrefix>62</PhonePrefix>
    <DomainExtension>.id</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>IE</Code>
    <Alpha3Code>IRL</Alpha3Code>
    <NumericCode>372</NumericCode>
    <Name>Ireland</Name>
    <PhonePrefix>353</PhonePrefix>
    <DomainExtension>.ie</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>IL</Code>
    <Alpha3Code>ISR</Alpha3Code>
    <NumericCode>376</NumericCode>
    <Name>Israel</Name>
    <PhonePrefix>972</PhonePrefix>
    <DomainExtension>.il</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>IM</Code>
    <Alpha3Code>IMN</Alpha3Code>
    <Name>Isle of Man</Name>
    <PhonePrefix>44</PhonePrefix>
    <DomainExtension>.im</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>IN</Code>
    <Alpha3Code>IND</Alpha3Code>
    <NumericCode>356</NumericCode>
    <Name>India</Name>
    <PhonePrefix>91</PhonePrefix>
    <DomainExtension>.in</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>IO</Code>
    <Alpha3Code>IOT</Alpha3Code>
    <NumericCode>86</NumericCode>
    <Name>Diego Garcia</Name>
    <PhonePrefix>0</PhonePrefix>
    <DomainExtension>.io</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>IQ</Code>
    <Alpha3Code>IRQ</Alpha3Code>
    <NumericCode>368</NumericCode>
    <Name>Iraq</Name>
    <PhonePrefix>964</PhonePrefix>
    <DomainExtension>.iq</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>IR</Code>
    <Alpha3Code>IRN</Alpha3Code>
    <NumericCode>364</NumericCode>
    <Name>Iran</Name>
    <PhonePrefix>98</PhonePrefix>
    <DomainExtension>.ir</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>IS</Code>
    <Alpha3Code>ISL</Alpha3Code>
    <NumericCode>352</NumericCode>
    <Name>Iceland</Name>
    <PhonePrefix>354</PhonePrefix>
    <DomainExtension>.is</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>IT</Code>
    <Alpha3Code>ITA</Alpha3Code>
    <NumericCode>380</NumericCode>
    <Name>Italy</Name>
    <PhonePrefix>39</PhonePrefix>
    <DomainExtension>.it</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>JM</Code>
    <Alpha3Code>JAM</Alpha3Code>
    <NumericCode>388</NumericCode>
    <Name>Jamaica</Name>
    <PhonePrefix>1876</PhonePrefix>
    <DomainExtension>.jm</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>JO</Code>
    <Alpha3Code>JOR</Alpha3Code>
    <NumericCode>400</NumericCode>
    <Name>Jordan</Name>
    <PhonePrefix>962</PhonePrefix>
    <DomainExtension>.jo</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>JP</Code>
    <Alpha3Code>JPN</Alpha3Code>
    <NumericCode>392</NumericCode>
    <Name>Japan</Name>
    <PhonePrefix>81</PhonePrefix>
    <DomainExtension>.jp</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>KE</Code>
    <Alpha3Code>KEN</Alpha3Code>
    <NumericCode>404</NumericCode>
    <Name>Kenya</Name>
    <PhonePrefix>254</PhonePrefix>
    <DomainExtension>.ke</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>KG</Code>
    <Alpha3Code>KGZ</Alpha3Code>
    <NumericCode>417</NumericCode>
    <Name>Kyrgyzstan</Name>
    <PhonePrefix>996</PhonePrefix>
    <DomainExtension>.kg</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>KH</Code>
    <Alpha3Code>KHM</Alpha3Code>
    <NumericCode>116</NumericCode>
    <Name>Cambodia</Name>
    <PhonePrefix>855</PhonePrefix>
    <DomainExtension>.kh</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>KI</Code>
    <Alpha3Code>KIR</Alpha3Code>
    <NumericCode>296</NumericCode>
    <Name>Kiribati</Name>
    <PhonePrefix>686</PhonePrefix>
    <DomainExtension>.ki</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>KM</Code>
    <Alpha3Code>COM</Alpha3Code>
    <NumericCode>174</NumericCode>
    <Name>Comoros</Name>
    <PhonePrefix>269</PhonePrefix>
    <DomainExtension>.km</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>KN</Code>
    <Alpha3Code>KNA</Alpha3Code>
    <NumericCode>659</NumericCode>
    <Name>Nevis</Name>
    <PhonePrefix>1869</PhonePrefix>
    <DomainExtension>.kn</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>KP</Code>
    <Alpha3Code>PRK</Alpha3Code>
    <NumericCode>408</NumericCode>
    <Name>North Korea</Name>
    <PhonePrefix>850</PhonePrefix>
    <DomainExtension>.kp</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>KR</Code>
    <Alpha3Code>KOR</Alpha3Code>
    <NumericCode>410</NumericCode>
    <Name>South Korea</Name>
    <PhonePrefix>82</PhonePrefix>
    <DomainExtension>.kr</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>KW</Code>
    <Alpha3Code>KWT</Alpha3Code>
    <NumericCode>414</NumericCode>
    <Name>Kuwait</Name>
    <PhonePrefix>965</PhonePrefix>
    <DomainExtension>.kw</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>KY</Code>
    <Alpha3Code>CYM</Alpha3Code>
    <NumericCode>136</NumericCode>
    <Name>Cayman Islands</Name>
    <PhonePrefix>1345</PhonePrefix>
    <DomainExtension>.ky</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>KZ</Code>
    <Alpha3Code>KAZ</Alpha3Code>
    <NumericCode>398</NumericCode>
    <Name>Kazakhstan</Name>
    <PhonePrefix>7</PhonePrefix>
    <DomainExtension>.kz</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>LA</Code>
    <Alpha3Code>LAO</Alpha3Code>
    <NumericCode>418</NumericCode>
    <Name>Laos</Name>
    <PhonePrefix>856</PhonePrefix>
    <DomainExtension>.la</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>LB</Code>
    <Alpha3Code>LBN</Alpha3Code>
    <NumericCode>422</NumericCode>
    <Name>Lebanon</Name>
    <PhonePrefix>961</PhonePrefix>
    <DomainExtension>.lb</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>LC</Code>
    <Alpha3Code>LCA</Alpha3Code>
    <NumericCode>662</NumericCode>
    <Name>St. Lucia</Name>
    <PhonePrefix>1758</PhonePrefix>
    <DomainExtension>.lc</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>LI</Code>
    <Alpha3Code>LIE</Alpha3Code>
    <NumericCode>438</NumericCode>
    <Name>Liechtenstein</Name>
    <PhonePrefix>423</PhonePrefix>
    <DomainExtension>.li</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>LK</Code>
    <Alpha3Code>LKA</Alpha3Code>
    <NumericCode>144</NumericCode>
    <Name>Sri Lanka</Name>
    <PhonePrefix>94</PhonePrefix>
    <DomainExtension>.lk</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>LR</Code>
    <Alpha3Code>LBR</Alpha3Code>
    <NumericCode>430</NumericCode>
    <Name>Liberia</Name>
    <PhonePrefix>231</PhonePrefix>
    <DomainExtension>.lr</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>LS</Code>
    <Alpha3Code>LSO</Alpha3Code>
    <NumericCode>426</NumericCode>
    <Name>Lesotho</Name>
    <PhonePrefix>266</PhonePrefix>
    <DomainExtension>.ls</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>LT</Code>
    <Alpha3Code>LTU</Alpha3Code>
    <NumericCode>440</NumericCode>
    <Name>Lithuania</Name>
    <PhonePrefix>370</PhonePrefix>
    <DomainExtension>.lt</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>LU</Code>
    <Alpha3Code>LUX</Alpha3Code>
    <NumericCode>442</NumericCode>
    <Name>Luxembourg</Name>
    <PhonePrefix>352</PhonePrefix>
    <DomainExtension>.lu</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>LV</Code>
    <Alpha3Code>LVA</Alpha3Code>
    <NumericCode>428</NumericCode>
    <Name>Latvia</Name>
    <PhonePrefix>371</PhonePrefix>
    <DomainExtension>.lv</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>LY</Code>
    <Alpha3Code>LBY</Alpha3Code>
    <NumericCode>434</NumericCode>
    <Name>Libya</Name>
    <PhonePrefix>218</PhonePrefix>
    <DomainExtension>.ly</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>MA</Code>
    <Alpha3Code>MAR</Alpha3Code>
    <NumericCode>504</NumericCode>
    <Name>Morocco</Name>
    <PhonePrefix>212</PhonePrefix>
    <DomainExtension>.ma</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>MC</Code>
    <Alpha3Code>MCO</Alpha3Code>
    <NumericCode>492</NumericCode>
    <Name>Monaco</Name>
    <PhonePrefix>377</PhonePrefix>
    <DomainExtension>.mc</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>MD</Code>
    <Alpha3Code>MDA</Alpha3Code>
    <NumericCode>498</NumericCode>
    <Name>Moldova</Name>
    <PhonePrefix>373</PhonePrefix>
    <DomainExtension>.md</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>ME</Code>
    <Alpha3Code>MNE</Alpha3Code>
    <NumericCode>499</NumericCode>
    <Name>Montenegro</Name>
    <PhonePrefix>382</PhonePrefix>
    <DomainExtension>.me</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>MG</Code>
    <Alpha3Code>MDG</Alpha3Code>
    <NumericCode>450</NumericCode>
    <Name>Madagascar</Name>
    <PhonePrefix>261</PhonePrefix>
    <DomainExtension>.mg</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>MH</Code>
    <Alpha3Code>MHL</Alpha3Code>
    <NumericCode>584</NumericCode>
    <Name>Marshall Islands</Name>
    <PhonePrefix>692</PhonePrefix>
    <DomainExtension>.mh</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>MK</Code>
    <Alpha3Code>MKD</Alpha3Code>
    <NumericCode>807</NumericCode>
    <Name>Macedonia</Name>
    <PhonePrefix>389</PhonePrefix>
    <DomainExtension>.mk</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>ML</Code>
    <Alpha3Code>MLI</Alpha3Code>
    <NumericCode>466</NumericCode>
    <Name>Mali Republic</Name>
    <PhonePrefix>223</PhonePrefix>
    <DomainExtension>.ml</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>MM</Code>
    <Alpha3Code>MMR</Alpha3Code>
    <NumericCode>104</NumericCode>
    <Name>Myanmar</Name>
    <PhonePrefix>95</PhonePrefix>
    <DomainExtension>.mm</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>MN</Code>
    <Alpha3Code>MNG</Alpha3Code>
    <NumericCode>496</NumericCode>
    <Name>Mongolia</Name>
    <PhonePrefix>976</PhonePrefix>
    <DomainExtension>.mn</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>MO</Code>
    <Alpha3Code>MAC</Alpha3Code>
    <NumericCode>446</NumericCode>
    <Name>Macau</Name>
    <PhonePrefix>853</PhonePrefix>
    <DomainExtension>.mo</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>MP</Code>
    <Alpha3Code>MNP</Alpha3Code>
    <NumericCode>580</NumericCode>
    <Name>Saipan</Name>
    <PhonePrefix>1670</PhonePrefix>
    <DomainExtension>.mp</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>MQ</Code>
    <Alpha3Code>MTQ</Alpha3Code>
    <NumericCode>474</NumericCode>
    <Name>Martinique</Name>
    <PhonePrefix></PhonePrefix>
    <DomainExtension>.mq</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>MR</Code>
    <Alpha3Code>MRT</Alpha3Code>
    <NumericCode>478</NumericCode>
    <Name>Mauritania</Name>
    <PhonePrefix>222</PhonePrefix>
    <DomainExtension>.mr</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>MS</Code>
    <Alpha3Code>MSR</Alpha3Code>
    <NumericCode>500</NumericCode>
    <Name>Montserrat</Name>
    <PhonePrefix>1664</PhonePrefix>
    <DomainExtension>.ms</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>MT</Code>
    <Alpha3Code>MLT</Alpha3Code>
    <NumericCode>470</NumericCode>
    <Name>Malta</Name>
    <PhonePrefix>356</PhonePrefix>
    <DomainExtension>.mt</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>MU</Code>
    <Alpha3Code>MUS</Alpha3Code>
    <NumericCode>480</NumericCode>
    <Name>Mauritius</Name>
    <PhonePrefix>230</PhonePrefix>
    <DomainExtension>.mu</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>MV</Code>
    <Alpha3Code>MDV</Alpha3Code>
    <NumericCode>462</NumericCode>
    <Name>Maldives</Name>
    <PhonePrefix>960</PhonePrefix>
    <DomainExtension>.mv</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>MW</Code>
    <Alpha3Code>MWI</Alpha3Code>
    <NumericCode>454</NumericCode>
    <Name>Malawi</Name>
    <PhonePrefix>265</PhonePrefix>
    <DomainExtension>.mw</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>MX</Code>
    <Alpha3Code>MEX</Alpha3Code>
    <NumericCode>484</NumericCode>
    <Name>Mexico</Name>
    <PhonePrefix>52</PhonePrefix>
    <DomainExtension>.mx</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>MY</Code>
    <Alpha3Code>MYS</Alpha3Code>
    <NumericCode>458</NumericCode>
    <Name>Malaysia</Name>
    <PhonePrefix>60</PhonePrefix>
    <DomainExtension>.my</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>MZ</Code>
    <Alpha3Code>MOZ</Alpha3Code>
    <NumericCode>508</NumericCode>
    <Name>Mozambique</Name>
    <PhonePrefix>258</PhonePrefix>
    <DomainExtension>.mz</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>NA</Code>
    <Alpha3Code>NAM</Alpha3Code>
    <NumericCode>516</NumericCode>
    <Name>Namibia</Name>
    <PhonePrefix>264</PhonePrefix>
    <DomainExtension>.na</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>NC</Code>
    <Alpha3Code>NCL</Alpha3Code>
    <NumericCode>540</NumericCode>
    <Name>New Caledonia</Name>
    <PhonePrefix>687</PhonePrefix>
    <DomainExtension>.nc</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>NE</Code>
    <Alpha3Code>NER</Alpha3Code>
    <NumericCode>562</NumericCode>
    <Name>Niger Republic</Name>
    <PhonePrefix>227</PhonePrefix>
    <DomainExtension>.ne</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>NF</Code>
    <Alpha3Code>NFK</Alpha3Code>
    <NumericCode>574</NumericCode>
    <Name>Norfolk Island</Name>
    <PhonePrefix></PhonePrefix>
    <DomainExtension>.nf</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>NG</Code>
    <Alpha3Code>NGA</Alpha3Code>
    <NumericCode>566</NumericCode>
    <Name>Nigeria</Name>
    <PhonePrefix>234</PhonePrefix>
    <DomainExtension>.ng</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>NI</Code>
    <Alpha3Code>NIC</Alpha3Code>
    <NumericCode>558</NumericCode>
    <Name>Nicaragua</Name>
    <PhonePrefix>505</PhonePrefix>
    <DomainExtension>.ni</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>NL</Code>
    <Alpha3Code>NLD</Alpha3Code>
    <NumericCode>528</NumericCode>
    <Name>Netherlands</Name>
    <PhonePrefix>31</PhonePrefix>
    <DomainExtension>.nl</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>NO</Code>
    <Alpha3Code>NOR</Alpha3Code>
    <NumericCode>578</NumericCode>
    <Name>Norway</Name>
    <PhonePrefix>47</PhonePrefix>
    <DomainExtension>.no</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>NP</Code>
    <Alpha3Code>NPL</Alpha3Code>
    <NumericCode>524</NumericCode>
    <Name>Nepal</Name>
    <PhonePrefix>977</PhonePrefix>
    <DomainExtension>.np</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>NR</Code>
    <Alpha3Code>NRU</Alpha3Code>
    <NumericCode>520</NumericCode>
    <Name>Nauru</Name>
    <PhonePrefix>674</PhonePrefix>
    <DomainExtension>.nr</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>NU</Code>
    <Alpha3Code>NIU</Alpha3Code>
    <NumericCode>570</NumericCode>
    <Name>Niue</Name>
    <PhonePrefix>683</PhonePrefix>
    <DomainExtension>.nu</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>NZ</Code>
    <Alpha3Code>NZL</Alpha3Code>
    <NumericCode>554</NumericCode>
    <Name>New Zealand</Name>
    <PhonePrefix>64</PhonePrefix>
    <DomainExtension>.nz</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>OM</Code>
    <Alpha3Code>OMN</Alpha3Code>
    <NumericCode>512</NumericCode>
    <Name>Oman</Name>
    <PhonePrefix>968</PhonePrefix>
    <DomainExtension>.om</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>PA</Code>
    <Alpha3Code>PAN</Alpha3Code>
    <NumericCode>591</NumericCode>
    <Name>Panama</Name>
    <PhonePrefix>507</PhonePrefix>
    <DomainExtension>.pa</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>PE</Code>
    <Alpha3Code>PER</Alpha3Code>
    <NumericCode>604</NumericCode>
    <Name>Peru</Name>
    <PhonePrefix>51</PhonePrefix>
    <DomainExtension>.pe</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>PF</Code>
    <Alpha3Code>PYF</Alpha3Code>
    <NumericCode>258</NumericCode>
    <Name>French Polynesia</Name>
    <PhonePrefix>689</PhonePrefix>
    <DomainExtension>.pf</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>PG</Code>
    <Alpha3Code>PNG</Alpha3Code>
    <NumericCode>598</NumericCode>
    <Name>Papua New Guinea</Name>
    <PhonePrefix>675</PhonePrefix>
    <DomainExtension>.pg</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>PH</Code>
    <Alpha3Code>PHL</Alpha3Code>
    <NumericCode>608</NumericCode>
    <Name>Philippines</Name>
    <PhonePrefix>63</PhonePrefix>
    <DomainExtension>.ph</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>PK</Code>
    <Alpha3Code>PAK</Alpha3Code>
    <NumericCode>586</NumericCode>
    <Name>Pakistan</Name>
    <PhonePrefix>92</PhonePrefix>
    <DomainExtension>.pk</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>PL</Code>
    <Alpha3Code>POL</Alpha3Code>
    <NumericCode>616</NumericCode>
    <Name>Poland</Name>
    <PhonePrefix>48</PhonePrefix>
    <DomainExtension>.pl</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>PM</Code>
    <Alpha3Code>SPM</Alpha3Code>
    <NumericCode>666</NumericCode>
    <Name>St. Pierre and Miquelon</Name>
    <PhonePrefix>508</PhonePrefix>
    <DomainExtension>.pm</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>PR</Code>
    <Alpha3Code>PRI</Alpha3Code>
    <NumericCode>630</NumericCode>
    <Name>Puerto Rico</Name>
    <PhonePrefix>1</PhonePrefix>
    <DomainExtension>.pr</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>PS</Code>
    <Alpha3Code>PSE</Alpha3Code>
    <Name>Palestine</Name>
    <PhonePrefix></PhonePrefix>
    <DomainExtension>.ps</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>PT</Code>
    <Alpha3Code>PRT</Alpha3Code>
    <NumericCode>620</NumericCode>
    <Name>Portugal</Name>
    <PhonePrefix>351</PhonePrefix>
    <DomainExtension>.pt</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>PW</Code>
    <Alpha3Code>PLW</Alpha3Code>
    <NumericCode>585</NumericCode>
    <Name>Palau</Name>
    <PhonePrefix>680</PhonePrefix>
    <DomainExtension>.pw</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>PY</Code>
    <Alpha3Code>PRY</Alpha3Code>
    <NumericCode>600</NumericCode>
    <Name>Paraguay</Name>
    <PhonePrefix>595</PhonePrefix>
    <DomainExtension>.py</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>QA</Code>
    <Alpha3Code>QAT</Alpha3Code>
    <NumericCode>634</NumericCode>
    <Name>Qatar</Name>
    <PhonePrefix>974</PhonePrefix>
    <DomainExtension>.qa</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>RE</Code>
    <Alpha3Code>REU</Alpha3Code>
    <NumericCode>638</NumericCode>
    <Name>Reunion Island</Name>
    <PhonePrefix></PhonePrefix>
    <DomainExtension>.re</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>RO</Code>
    <Alpha3Code>ROU</Alpha3Code>
    <NumericCode>642</NumericCode>
    <Name>Romania</Name>
    <PhonePrefix>40</PhonePrefix>
    <DomainExtension>.ro</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>RS</Code>
    <Alpha3Code>SRB</Alpha3Code>
    <NumericCode>688</NumericCode>
    <Name>Serbia</Name>
    <PhonePrefix>381</PhonePrefix>
    <DomainExtension>.rs</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>RU</Code>
    <Alpha3Code>RUS</Alpha3Code>
    <NumericCode>643</NumericCode>
    <Name>Russia</Name>
    <PhonePrefix>7</PhonePrefix>
    <DomainExtension>.ru</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>RW</Code>
    <Alpha3Code>RWA</Alpha3Code>
    <NumericCode>646</NumericCode>
    <Name>Rwanda</Name>
    <PhonePrefix>250</PhonePrefix>
    <DomainExtension>.rw</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>SA</Code>
    <Alpha3Code>SAU</Alpha3Code>
    <NumericCode>682</NumericCode>
    <Name>Saudi Arabia</Name>
    <PhonePrefix>966</PhonePrefix>
    <DomainExtension>.sa</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>SB</Code>
    <Alpha3Code>SLB</Alpha3Code>
    <NumericCode>90</NumericCode>
    <Name>Solomon Islands</Name>
    <PhonePrefix>677</PhonePrefix>
    <DomainExtension>.sb</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>SC</Code>
    <Alpha3Code>SYC</Alpha3Code>
    <NumericCode>690</NumericCode>
    <Name>Seychelles</Name>
    <PhonePrefix>248</PhonePrefix>
    <DomainExtension>.sc</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>SD</Code>
    <Alpha3Code>SDN</Alpha3Code>
    <NumericCode>736</NumericCode>
    <Name>Sudan</Name>
    <PhonePrefix>249</PhonePrefix>
    <DomainExtension>.sd</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>SE</Code>
    <Alpha3Code>SWE</Alpha3Code>
    <NumericCode>752</NumericCode>
    <Name>Sweden</Name>
    <PhonePrefix>46</PhonePrefix>
    <DomainExtension>.se</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>SG</Code>
    <Alpha3Code>SGP</Alpha3Code>
    <NumericCode>702</NumericCode>
    <Name>Singapore</Name>
    <PhonePrefix>65</PhonePrefix>
    <DomainExtension>.sg</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>SH</Code>
    <Alpha3Code>SHN</Alpha3Code>
    <NumericCode>654</NumericCode>
    <Name>St. Helena</Name>
    <PhonePrefix>290</PhonePrefix>
    <DomainExtension>.sh</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>SI</Code>
    <Alpha3Code>SVN</Alpha3Code>
    <NumericCode>705</NumericCode>
    <Name>Slovenia</Name>
    <PhonePrefix>386</PhonePrefix>
    <DomainExtension>.si</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>SK</Code>
    <Alpha3Code>SVK</Alpha3Code>
    <NumericCode>703</NumericCode>
    <Name>Slovakia</Name>
    <PhonePrefix>421</PhonePrefix>
    <DomainExtension>.sk</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>SL</Code>
    <Alpha3Code>SLE</Alpha3Code>
    <NumericCode>694</NumericCode>
    <Name>Sierra Leone</Name>
    <PhonePrefix>232</PhonePrefix>
    <DomainExtension>.sl</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>SM</Code>
    <Alpha3Code>SMR</Alpha3Code>
    <NumericCode>674</NumericCode>
    <Name>San Marino</Name>
    <PhonePrefix>378</PhonePrefix>
    <DomainExtension>.sm</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>SN</Code>
    <Alpha3Code>SEN</Alpha3Code>
    <NumericCode>686</NumericCode>
    <Name>Senegal Republic</Name>
    <PhonePrefix>221</PhonePrefix>
    <DomainExtension>.sn</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>SO</Code>
    <Alpha3Code>SOM</Alpha3Code>
    <NumericCode>706</NumericCode>
    <Name>Somalia Republic</Name>
    <PhonePrefix>252</PhonePrefix>
    <DomainExtension>.so</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>SR</Code>
    <Alpha3Code>SUR</Alpha3Code>
    <NumericCode>740</NumericCode>
    <Name>Suriname</Name>
    <PhonePrefix>597</PhonePrefix>
    <DomainExtension>.sr</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>SS</Code>
    <Alpha3Code>SSD</Alpha3Code>
    <NumericCode>710</NumericCode>
    <Name>South Sudan</Name>
    <PhonePrefix></PhonePrefix>
    <DomainExtension>.ss</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>ST</Code>
    <Alpha3Code>STP</Alpha3Code>
    <NumericCode>678</NumericCode>
    <Name>Sao Tome</Name>
    <PhonePrefix>239</PhonePrefix>
    <DomainExtension>.st</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>SV</Code>
    <Alpha3Code>SLV</Alpha3Code>
    <NumericCode>222</NumericCode>
    <Name>El Salvador</Name>
    <PhonePrefix>503</PhonePrefix>
    <DomainExtension>.sv</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>SX</Code>
    <Alpha3Code>SXM</Alpha3Code>
    <Name>Sint Maarten</Name>
    <PhonePrefix></PhonePrefix>
    <DomainExtension>.sx</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>SY</Code>
    <Alpha3Code>SYR</Alpha3Code>
    <NumericCode>760</NumericCode>
    <Name>Syria</Name>
    <PhonePrefix>963</PhonePrefix>
    <DomainExtension>.sy</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>SZ</Code>
    <Alpha3Code>SWZ</Alpha3Code>
    <NumericCode>748</NumericCode>
    <Name>Swaziland</Name>
    <PhonePrefix>268</PhonePrefix>
    <DomainExtension>.sz</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>TC</Code>
    <Alpha3Code>TCA</Alpha3Code>
    <NumericCode>796</NumericCode>
    <Name>Turks and Caicos Islands</Name>
    <PhonePrefix>1649</PhonePrefix>
    <DomainExtension>.tc</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>TD</Code>
    <Alpha3Code>TCD</Alpha3Code>
    <NumericCode>148</NumericCode>
    <Name>Chad Republic</Name>
    <PhonePrefix>235</PhonePrefix>
    <DomainExtension>.td</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>TG</Code>
    <Alpha3Code>TGO</Alpha3Code>
    <NumericCode>768</NumericCode>
    <Name>Togo</Name>
    <PhonePrefix>228</PhonePrefix>
    <DomainExtension>.tg</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>TH</Code>
    <Alpha3Code>THA</Alpha3Code>
    <NumericCode>764</NumericCode>
    <Name>Thailand</Name>
    <PhonePrefix>66</PhonePrefix>
    <DomainExtension>.th</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>TJ</Code>
    <Alpha3Code>TJK</Alpha3Code>
    <NumericCode>762</NumericCode>
    <Name>Tajikistan</Name>
    <PhonePrefix>992</PhonePrefix>
    <DomainExtension>.tj</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>TK</Code>
    <Alpha3Code>TKL</Alpha3Code>
    <NumericCode>772</NumericCode>
    <Name>Tokelau</Name>
    <PhonePrefix>690</PhonePrefix>
    <DomainExtension>.tk</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>TL</Code>
    <Alpha3Code>TLS</Alpha3Code>
    <Name>East Timor</Name>
    <PhonePrefix>670</PhonePrefix>
    <DomainExtension>.tl</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>TM</Code>
    <Alpha3Code>TKM</Alpha3Code>
    <NumericCode>795</NumericCode>
    <Name>Turkmenistan</Name>
    <PhonePrefix>993</PhonePrefix>
    <DomainExtension>.tm</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>TN</Code>
    <Alpha3Code>TUN</Alpha3Code>
    <NumericCode>788</NumericCode>
    <Name>Tunisia</Name>
    <PhonePrefix>216</PhonePrefix>
    <DomainExtension>.tn</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>TO</Code>
    <Alpha3Code>TON</Alpha3Code>
    <NumericCode>776</NumericCode>
    <Name>Tonga</Name>
    <PhonePrefix>676</PhonePrefix>
    <DomainExtension>.to</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>TR</Code>
    <Alpha3Code>TUR</Alpha3Code>
    <NumericCode>792</NumericCode>
    <Name>Turkey</Name>
    <PhonePrefix>90</PhonePrefix>
    <DomainExtension>.tr</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>TT</Code>
    <Alpha3Code>TTO</Alpha3Code>
    <NumericCode>780</NumericCode>
    <Name>Trinidad and Tobago</Name>
    <PhonePrefix>1868</PhonePrefix>
    <DomainExtension>.tt</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>TV</Code>
    <Alpha3Code>TUV</Alpha3Code>
    <NumericCode>798</NumericCode>
    <Name>Tuvalu</Name>
    <PhonePrefix>688</PhonePrefix>
    <DomainExtension>.tv</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>TW</Code>
    <Alpha3Code>TWN</Alpha3Code>
    <NumericCode>158</NumericCode>
    <Name>Taiwan</Name>
    <PhonePrefix>886</PhonePrefix>
    <DomainExtension>.tw</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>TZ</Code>
    <Alpha3Code>TZA</Alpha3Code>
    <NumericCode>834</NumericCode>
    <Name>Tanzania</Name>
    <PhonePrefix>255</PhonePrefix>
    <DomainExtension>.tz</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>UA</Code>
    <Alpha3Code>UKR</Alpha3Code>
    <NumericCode>804</NumericCode>
    <Name>Ukraine</Name>
    <PhonePrefix>380</PhonePrefix>
    <DomainExtension>.ua</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>UG</Code>
    <Alpha3Code>UGA</Alpha3Code>
    <NumericCode>800</NumericCode>
    <Name>Uganda</Name>
    <PhonePrefix>256</PhonePrefix>
    <DomainExtension>.ug</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>UM</Code>
    <Alpha3Code>UMI</Alpha3Code>
    <NumericCode>581</NumericCode>
    <Name>Midway Islands</Name>
    <PhonePrefix></PhonePrefix>
    <DomainExtension>.um</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>US</Code>
    <Alpha3Code>USA</Alpha3Code>
    <NumericCode>840</NumericCode>
    <Name>United States</Name>
    <PhonePrefix>1</PhonePrefix>
    <DomainExtension>.us</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>UY</Code>
    <Alpha3Code>URY</Alpha3Code>
    <NumericCode>858</NumericCode>
    <Name>Uruguay</Name>
    <PhonePrefix>598</PhonePrefix>
    <DomainExtension>.uy</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>UZ</Code>
    <Alpha3Code>UZB</Alpha3Code>
    <NumericCode>860</NumericCode>
    <Name>Uzbekistan</Name>
    <PhonePrefix>998</PhonePrefix>
    <DomainExtension>.uz</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>VA</Code>
    <Alpha3Code>VAT</Alpha3Code>
    <NumericCode>336</NumericCode>
    <Name>Vatican city</Name>
    <PhonePrefix>39</PhonePrefix>
    <DomainExtension>.va</DomainExtension>
    <ContinentID>4</ContinentID>
  </item>
  <item>
    <Code>VC</Code>
    <Alpha3Code>VCT</Alpha3Code>
    <NumericCode>670</NumericCode>
    <Name>St. Vincent</Name>
    <PhonePrefix>1784</PhonePrefix>
    <DomainExtension>.vc</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>VE</Code>
    <Alpha3Code>VEN</Alpha3Code>
    <NumericCode>862</NumericCode>
    <Name>Venezuela</Name>
    <PhonePrefix>58</PhonePrefix>
    <DomainExtension>.ve</DomainExtension>
    <ContinentID>7</ContinentID>
  </item>
  <item>
    <Code>VG</Code>
    <Alpha3Code>VGB</Alpha3Code>
    <NumericCode>92</NumericCode>
    <Name>British Virgin Islands</Name>
    <PhonePrefix>1284</PhonePrefix>
    <DomainExtension>.vg</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>VI</Code>
    <Alpha3Code>VIR</Alpha3Code>
    <NumericCode>850</NumericCode>
    <Name>US Virgin Islands</Name>
    <PhonePrefix>1340</PhonePrefix>
    <DomainExtension>.vi</DomainExtension>
    <ContinentID>5</ContinentID>
  </item>
  <item>
    <Code>VN</Code>
    <Alpha3Code>VNM</Alpha3Code>
    <NumericCode>704</NumericCode>
    <Name>Vietnam</Name>
    <PhonePrefix>84</PhonePrefix>
    <DomainExtension>.vn</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>VU</Code>
    <Alpha3Code>VUT</Alpha3Code>
    <NumericCode>548</NumericCode>
    <Name>Vanuatu</Name>
    <PhonePrefix>678</PhonePrefix>
    <DomainExtension>.vu</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>WF</Code>
    <Alpha3Code>WLF</Alpha3Code>
    <NumericCode>876</NumericCode>
    <Name>Wallis and Futuna Islands</Name>
    <PhonePrefix>681</PhonePrefix>
    <DomainExtension>.wf</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>WS</Code>
    <Alpha3Code>WSM</Alpha3Code>
    <NumericCode>882</NumericCode>
    <Name>Samoa</Name>
    <PhonePrefix>685</PhonePrefix>
    <DomainExtension>.ws</DomainExtension>
    <ContinentID>6</ContinentID>
  </item>
  <item>
    <Code>YE</Code>
    <Alpha3Code>YEM</Alpha3Code>
    <NumericCode>887</NumericCode>
    <Name>Yemen</Name>
    <PhonePrefix>967</PhonePrefix>
    <DomainExtension>.ye</DomainExtension>
    <ContinentID>3</ContinentID>
  </item>
  <item>
    <Code>YT</Code>
    <Alpha3Code>MYT</Alpha3Code>
    <NumericCode>175</NumericCode>
    <Name>Mayotte Island</Name>
    <PhonePrefix>262</PhonePrefix>
    <DomainExtension>.yt</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>ZA</Code>
    <Alpha3Code>ZAF</Alpha3Code>
    <NumericCode>729</NumericCode>
    <Name>South Africa</Name>
    <PhonePrefix>27</PhonePrefix>
    <DomainExtension>.za</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>ZM</Code>
    <Alpha3Code>ZMB</Alpha3Code>
    <NumericCode>894</NumericCode>
    <Name>Zambia</Name>
    <PhonePrefix>260</PhonePrefix>
    <DomainExtension>.zm</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
  <item>
    <Code>ZW</Code>
    <Alpha3Code>ZWE</Alpha3Code>
    <NumericCode>716</NumericCode>
    <Name>Zimbabwe</Name>
    <PhonePrefix>263</PhonePrefix>
    <DomainExtension>.zw</DomainExtension>
    <ContinentID>1</ContinentID>
  </item>
</items>'

EXEC sp_xml_preparedocument @idoc OUTPUT, @data

INSERT INTO Country(Code, Alpha3Code, NumericCode, Name, PhonePrefix, DomainExtension, ContinentID)
SELECT   * 
FROM     OPENXML (@idoc, 'items/item',2) 
            WITH (
				Code CHAR(2),
				Alpha3Code CHAR(3),
				NumericCode SMALLINT,
				Name    NVARCHAR (100),
				PhonePrefix VARCHAR(5), 
				DomainExtension VARCHAR(3), 
				ContinentID TINYINT)

GO
