//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easymish.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.FacilityAccounts = new HashSet<FacilityAccount>();
            this.FacilityProperties = new HashSet<FacilityProperty>();
            this.People = new HashSet<Person>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public Nullable<int> HeadquarterID { get; set; }
        public int Type { get; set; }
        public string Website { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime LModifyDate { get; set; }
        public int ModifyBy { get; set; }
    
        public virtual ICollection<FacilityAccount> FacilityAccounts { get; set; }
        public virtual ICollection<FacilityProperty> FacilityProperties { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
}
