//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easymish.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityAccount
    {
        public int ID { get; set; }
        public int FacilityID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime LModifyDate { get; set; }
        public int ModifyBy { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Person Person { get; set; }
    }
}
