//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easymish.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.FacilityAccounts = new HashSet<FacilityAccount>();
            this.PersonProfiles = new HashSet<PersonProfile>();
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual ICollection<FacilityAccount> FacilityAccounts { get; set; }
        public virtual ICollection<PersonProfile> PersonProfiles { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
